site_name: FS Link Documentation
extra_javascript:
  - ./js/main.js
  - ./api/fslink.v1.yaml
extra_css:
  - ./css/main.css
site_dir: ./site/
theme:
  name: 'rtd-dropdown'
  highlightjs: true
  hljs_languages:
        - yaml
        - rust
        - json
        - html
markdown_extensions:
    - toc:
        permalink: 